### ISSUE TITLE
Implement actual `clean_id` filter

### ISSUE THREAD

**Issue by fafnirical** [kalamuna/twig-drupal-filters#25]
There's a `clean_id` filter implemented already, but it doesn't use the same logic as Drupal's filter. We could port Drupal's to JavaScript:
https://git.drupalcode.org/project/drupal/blob/8.8.x/core/lib/Drupal/Core/Template/TwigExtension.php#L184
https://git.drupalcode.org/project/drupal/blob/8.8.x/core/lib/Drupal/Component/Utility/Html.php#L204-232

**Comment by RobLoach** [comment]
Would love for these to get in! :+1:

**Comment by fafnirical** [comment]
I'll create some PRs when I get a chance :)
